// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Transaction.Framework.Data;

#nullable disable

namespace Transaction.Framework.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230911165050_check")]
    partial class check
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Transaction.Framework.Data.Entities.AccountSummaryEntity", b =>
                {
                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Balance")
                        .IsConcurrencyToken()
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountNumber");

                    b.ToTable("AccountSummary", "dbo");

                    b.HasData(
                        new
                        {
                            AccountNumber = "1234567890",
                            Balance = 1000000m,
                            Currency = "IDR"
                        });
                });

            modelBuilder.Entity("Transaction.Framework.Data.Entities.AccountTransactionEntity", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"), 1L, 1);

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionId");

                    b.HasIndex("AccountNumber");

                    b.ToTable("AccountTransaction", "dbo");
                });

            modelBuilder.Entity("Transaction.Framework.Data.Entities.AccountTransactionEntity", b =>
                {
                    b.HasOne("Transaction.Framework.Data.Entities.AccountSummaryEntity", "AccountSummary")
                        .WithMany("AccountTransactions")
                        .HasForeignKey("AccountNumber");

                    b.Navigation("AccountSummary");
                });

            modelBuilder.Entity("Transaction.Framework.Data.Entities.AccountSummaryEntity", b =>
                {
                    b.Navigation("AccountTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
